### ISSUE TITLE
create test function for subtract

### ISSUE THREAD

**Issue by finalight** [finalight/calculator#2]
just write a test function for subtract, leave out the implementation

**Comment by vedanttttt** [comment]
Can you please tell what do you mean by this issue ?

**Comment by finalight** [comment]
the goal is to do TDD whereby you write test first then you write to fulfil this the test, but i split it out between test and code as separate issue.

so specifically for this issue. you only need to write a test to take in 2 numbers and return the difference

**Comment by vedanttttt** [comment]
> the goal is to do TDD whereby you write test first then you write to fulfil this the test, but i split it out between test and code as separate issue.
> 
> so specifically for this issue. you only need to write a test to take in 2 numbers and return the difference

Okay,thanks for telling

**Comment by finalight** [comment]
let me rename the issue title to make it more clear

**Comment by vedanttttt** [comment]
> let me rename the issue title to make it more clear

Should i do changes in index.js file ?

**Comment by finalight** [comment]
that should do fine
