### ISSUE TITLE
create test function for divide

### ISSUE THREAD

**Issue by finalight** [finalight/calculator#4]
just write the test for the divide function, leave out the implemtation first

**Comment by kumaranshu72** [comment]
can i pick this up?

**Comment by finalight** [comment]
sure by all means

**Comment by kumaranshu72** [comment]
@finalight can I use mocha instead of jest for writing the test cases?

**Comment by finalight** [comment]
i 've already set the baseline for using jest, i think it would be
preferable to stick with it

**Comment by sauravsolanki** [comment]
Assign me this please.

**Comment by sauravsolanki** [comment]
Done. @finalight

**Comment by amey-g** [comment]
can I do this? would you please assign this to me?

**Comment by sauravsolanki** [comment]
I have done this task... Waiting for author to merge. @amey-g
